### PR TITLE
Fix issue 79: Delete operation in Python example

### PR DESCRIPTION
**Pull request by abraarsyed**
Fix issue: https://github.com/saltedge/saltedge-examples/issues/79

Resolve:
1. Remove payload from Delete method in saltedge.py
2. Add missing example of delete_request.py in python folder

### CODE REVIEW

**Comment by abraarsyed** [comment]
Hey! Can I get help in reviewing this PR please?

**Comment by abraarsyed** [comment]
I have resolved the merge conflicts to my commits after the recent update from latest commits by other contributors. 
Please help review this PR!

**Comment by alexeisersun** [comment]
@abraarsyed Thanks for your contribution! Sorry for late reply. 😓

**Comment by abraarsyed** [comment]
Thank you @alexeisersun for the review and closing the PR :)

**Pull request merged**
